services:
  fastapi-app:
    image: tireni/fastapi-book-project:main
    container_name: fastapi-app
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine  
    container_name: nginx-container
    ports:
      - "80:80"  
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
      - /etc/letsencrypt:/etc/letsencrypt 
    depends_on:
      - fastapi-app
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge